### ISSUE TITLE
How to work with .svg files?

### ISSUE THREAD

**Issue by davidhtims** [sidthesloth92/vsc_svg_snippets#1]
I have this working with html files but I'd like to use this with a standalone svg file.
How do I do this please?

**Comment by brainary** [comment]
Seems the `package.json` from the VSCode Market Place doesn't match the one listed in this repo. The one on the Market Place only lists support for **HTML** files.

You can "fix" this by going into the directory the extension is installed in, default; `%USERPROFILE%\.vscode\extensions\sidthesloth.svg-snippets-1.0.0`

Open the `package.json`, scroll down to **contributes** and add support for **XML** and **SVG**.

**Comment by sidthesloth92** [comment]
Have published the changes as a part of 1.0.1. Closing the issue thanks @brainary .. :)
